/**
 * TypeScript declarations for @beamlab/solver-wasm
 * 
 * These types are generated by wasm-pack but we provide them here
 * for development before the WASM module is built.
 */

declare module '@beamlab/solver-wasm' {
  /** Initialize the WASM module */
  export default function init(): Promise<void>;

  /** Solve a linear system using LU decomposition */
  export function solve_system(
    stiffness_flat: Float64Array,
    force_array: Float64Array,
    n: number
  ): SolverResultWasm;

  /** Solve a sparse linear system */
  export function solve_sparse_system(
    row_indices: Uint32Array,
    col_indices: Uint32Array,
    values: Float64Array,
    force_array: Float64Array,
    n: number
  ): SolverResultWasm;

  /** Solve using Cholesky decomposition (for SPD matrices) */
  export function solve_cholesky(
    stiffness_flat: Float64Array,
    force_array: Float64Array,
    n: number
  ): SolverResultWasm;

  /** Solve using Conjugate Gradient method */
  export function solve_conjugate_gradient(
    stiffness_flat: Float64Array,
    force_array: Float64Array,
    n: number,
    max_iterations: number,
    tolerance: number
  ): SolverResultWasm;

  /** Get solver version */
  export function get_solver_version(): string;

  /** Check if WASM module is loaded correctly */
  export function health_check(): boolean;

  /** Run benchmark matrix multiplication */
  export function benchmark_multiply(size: number): number;

  /** Result from the WASM solver */
  interface SolverResultWasm {
    /** Displacement vector */
    displacements: number[];
    /** Whether the solve was successful */
    success: boolean;
    /** Error message if solve failed */
    error: string | null;
    /** Solve time in milliseconds */
    solve_time_ms: number;
    /** Solver method used */
    method: string;
    /** Matrix condition number estimate */
    condition_number: number | null;
  }
}
